name: Compile for Windows

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'


jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile for Windows
        shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cl /EHsc /Fe:source.exe source.c' }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source.exe
          asset_name: source.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
