name: Compile for Windows

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'


jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile for Windows
        shell: cmd
        run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cl /EHsc /Fe:source.exe source.c'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
          artifacts: source.exe
          artifactContentType: application/vnd.microsoft.portable-executable